SIM:
	ant build -Dmanager=qgddfe.qgdDFEManager -Dtarget=DFE_SIM -Dmaxfile-name=qgdDFE -Dresult-dir=/home/rakytap/qgd_DFE/qgdDFE/builds/simulation -Dengine_params=\"\"

DFE:
	ant build -Dmanager=qgddfe.qgdDFEManager -Dtarget=DFE -Dmaxfile-name=qgdDFE -Dresult-dir=/home/rakytap/qgd_DFE/qgdDFE/builds/bitstream -Dengine_params=\"\"

.PHONY:

